[
  { english: "cater", mandarin: "迎合" },
  { english: "budding poets", mandarin: "初出茅庐的诗人" },
  { english: "adjudge", mandarin: "宣判" },
  { english: "adjourned", mandarin: "休会" },
  { english: "impart", mandarin: "传授" },
  { english: "rival", mandarin: "竞争对手" },
  { english: "synonymous", mandarin: "同义的" },
  { english: "pampering", mandarin: "宠爱" },
  { english: "instill", mandarin: "灌输" },
  { english: "cultivate", mandarin: "培养" },
  { english: "counteract", mandarin: "对抗" },
  { english: "stalagmites", mandarin: "石笋" },
  { english: "pillars", mandarin: "柱子" },
  { english: "white water rafting", mandarin: "激流泛舟" },
  { english: "abseiling", mandarin: "绳索下降" },
  { english: "flying fox", mandarin: "飞狐" },
  { english: "canopy walk", mandarin: "树冠步道" },
  { english: "angling", mandarin: "钓鱼" },
  { english: "exotic", mandarin: "异国情调的" },
  { english: "chalets", mandarin: "小木屋" },
  { english: "canoeing", mandarin: "划独木舟" },
  { english: "game for it", mandarin: "愿意尝试的" },
  { english: "liaise", mandarin: "联络" },
  { english: "pursuits", mandarin: "追求" },
  { english: "comprising", mandarin: "包括" },
  { english: "haunt", mandarin: "经常出没的地方" },
  { english: "tedious", mandarin: "乏味的" },
  { english: "a breeze", mandarin: "轻而易举的事情" },
  { english: "cramming", mandarin: "死记硬背" },
  { english: "short bouts", mandarin: "短暂的时间" },
  { english: "keep tabs on", mandarin: "密切关注" },
  { english: "obedient", mandarin: "顺从的" },
  { english: "trot", mandarin: "小跑" },
  { english: "credentials", mandarin: "资格证书" },
  { english: "bias", mandarin: "偏见" },
  { english: "irresistible", mandarin: "不可抗拒的" },
  { english: "symbolizes", mandarin: "象征" },
  { english: "blurb", mandarin: "推销广告" },
  { english: "skim", mandarin: "略读" },
  { english: "credits", mandarin: "学分" },
  { english: "plough on", mandarin: "坚持下去" },
  { english: "peek", mandarin: "偷看" },
  { english: "off the mark", mandarin: "失误" },
  { english: "upheaval", mandarin: "剧变" },
  { english: "interprets", mandarin: "解释" },
  { english: "layman", mandarin: "外行人" },
  { english: "censorship", mandarin: "审查制度" },
  { english: "imposed", mandarin: "强制实施的" },
  { english: "detrimental", mandarin: "有害的" },
  { english: "stifle", mandarin: "压制" },
  { english: "desperately", mandarin: "极其渴望的" },
  { english: "rigorous of studying", mandarin: "苦学" },
  { english: "wilderness", mandarin: "荒野" },
  { english: "savour", mandarin: "品味" },
  { english: "adhere", mandarin: "坚持" },
  { english: "pensive", mandarin: "沉思的" },
  { english: "ravage", mandarin: "破坏" },
  { english: "spied", mandarin: "瞥见" },
  { english: "swirling", mandarin: "旋转的" },
  { english: "nerved", mandarin: "鼓起勇气" },
  { english: "solitude", mandarin: "孤独" },
  { english: "within earshot", mandarin: "听得见的范围内" },
  { english: "seeping", mandarin: "渗出" },
  { english: "coursed", mandarin: "流动" },
  { english: "weary", mandarin: "疲倦的" },
  { english: "uttered", mandarin: "发出" },
  { english: "kindred", mandarin: "同类的" },
  { english: "sanctuary", mandarin: "避难所" },
  { english: "proximity", mandarin: "接近" },
  { english: "wander off", mandarin: "闲逛" },
  { english: "occasion", mandarin: "时机" },
  { english: "chores", mandarin: "家务" },
  { english: "cited", mandarin: "引用" },
  { english: "nosy", mandarin: "爱管闲事的" },
  { english: "pry", mandarin: "打听" },
  { english: "all and sundry", mandarin: "所有人" },
  { english: "outstay", mandarin: "逗留过久" },
  { english: "anxiety", mandarin: "焦虑" },
  { english: "aviaries", mandarin: "鸟舍" },
  { english: "roam", mandarin: "漫步" },
  { english: "premises", mandarin: "地点" },
  { english: "soaring", mandarin: "飞翔的" },
  { english: "bulky", mandarin: "笨重的" },
  { english: "graceful", mandarin: "优雅的" },
  { english: "storks", mandarin: "鹳" },
  { english: "pheasants", mandarin: "雉" },
  { english: "fowls", mandarin: "家禽" },
  { english: "predators", mandarin: "捕食者" },
  { english: "bridge the gap", mandarin: "缩小差距" },
  { english: "empathy", mandarin: "同理心" },
  { english: "booth", mandarin: "亭子" },
  { english: "ramps", mandarin: "斜坡" },
  { english: "merriment", mandarin: "欢乐" },
  { english: "ancestor worship", mandarin: "祖先崇拜" },
  { english: "eve", mandarin: "前夕" },
  { english: "altar", mandarin: "祭坛" },
];
